<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ErrorHandler\Action\AbstractAction'  => __DIR__ . '/src/ErrorHandler/Action/AbstractAction.php',
    'ErrorHandler\Action\ActionInterface' => __DIR__ . '/src/ErrorHandler/Action/ActionInterface.php',
    'ErrorHandler\Action\SendMail'        => __DIR__ . '/src/ErrorHandler/Action/SendMail.php',
    'ErrorHandler\Action\Log'             => __DIR__ . '/src/ErrorHandler/Action/Log.php',
    'ErrorHandler\Model\Error'            => __DIR__ . '/src/ErrorHandler/Model/Error.php',
    'ErrorHandler\Module'                 => __DIR__ . '/src/Module.php',
);
